baseURL = 'https://georgeyw.github.io'
languageCode = 'en-us'
title = 'George Wang'
theme = 'cactus'

[params]
	colortheme = 'light'
	description = "This is a place for turning the stuff between my ears into words."
	mainSectionTitle = "Posts"

[[params.social]]
  name = "github"
  link = "https://github.com/georgeyw"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/georgeyw/"
	
[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "Posts"
	url = "/posts"
	weight = 2

[[menu.main]]
	name = "Games"
	url = "/games"
	weight = 3

[[menu.main]]
	name = "About/CV"
	url = "/about"
	weight = 4

